name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7]
        celery-version: [4.1, 4.2, 4.3]
        tornado-version: [5.0, 5.1]

    steps:
    - uses: actions/checkout@v1

    - name: Set up python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install celery==${{ matrix.celery-version }}
        pip install tornado==${{ matrix.tornado-version }}
        pip install -r requirements/default.txt
        pip install -r requirements/test.txt

    - name: Run unit tests
      run: |
        python -m flower --version
        python -m tests.unit.__main__

